#!/bin/bash

echo "正拷贝当前目录的所有codesnippet文件到 \"~/Library/Developer/Xcode/UserData/CodeSnippets/\"..."
cd `dirname $0`
cp -n ./*.codesnippet ~/Library/Developer/Xcode/UserData/CodeSnippets/
echo "all things done!🍻"
