#!/bin/bash
echo "pushing local changes to github repo..."
cd `dirname $0`
echo "1. push"
git pull;
echo ""

echo "2. add *"
git add *

gitStatusResult=`git status`
echo $gitStatusResult|grep "Changes to be committed"
if [[ $? == 1 ]]; then
	echo "当前无任何更新。即将退出。。。"
	exit 0;
else 
	echo "检查到本地有缓存起来的变更。。。"
fi
echo ""



echo "3. 手动输入提交日志?（选择n的话，提交日志为系统日期） y/n:"
read choice
message=`date`
if [[ $choice == y ]]; then
	echo -n "输入提交日志:"
	read message
fi
git commit -m "$message";
echo ""

echo "4. pushing"
git push
echo ""

echo "Done!🍻"