#!/bin/bash
echo "pushing local changes to github repo..."
cd `dirname $0`
echo "1. push"
git pull;
echo ""

echo "2. git status"
git status

echo "3. add *"
git add *;
echo ""

echo "4. commit local changes"
git commit -m "update at: `date`";
echo ""

echo "5. pushing"
git push
echo ""

echo "Done!🍻"