#!/bin/bash
echo "pushing local changes to github repo..."
cd `dirname $0`
echo "1. push"
git pull;
echo ""

echo "2. git status"
git status

echo "3. add *"
git add *;
echo ""

echo "4. 手动输入提交日志?（选择n的话，提交日志为系统日期） y/n:"
read choice
message=`date`
if [[ $choice == y ]]; then
	echo -n "输入提交日志:"
	read message
fi
git commit -m "$message";
echo ""

echo "5. pushing"
git push
echo ""

echo "Done!🍻"